title: Rise & Code
description: A programming book for everyone without access to computers
theme: minima
baseurl: "/rise-and-code"

# Build settings
markdown: kramdown
highlighter: rouge

# Enable GitHub Pages to process the site
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE