name: Build and Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin

      - name: Set up version info
        id: version
        run: |
          VERSION=$(date +'v%Y.%m.%d-%H%M')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATE=$(date +'%B %d, %Y')" >> $GITHUB_ENV

      - name: Create build directory
        run: mkdir -p build

      - name: Build PDF (Placeholder if PDF is missing)
        run: |
          if [ -f "build/rise-and-code.pdf" ] && [ -s "build/rise-and-code.pdf" ]; then
            echo "PDF file exists and has content"
          else
            echo "WARNING: PDF file is missing or empty, creating a placeholder"
            echo "# Rise & Code - Placeholder PDF" > build/placeholder.md
            pandoc build/placeholder.md -o build/rise-and-code.pdf --pdf-engine=xelatex
          fi

      - name: Build HTML page from PDF (Optional - Depending on Your Requirements)
        run: |
          # If you want to convert the PDF to HTML (for example, use tools like pdf2htmlEX or a custom script)
          echo "Building HTML page from PDF..."
          # Example: Convert PDF to HTML using a script or tool like `pdf2htmlEX`

      - name: Upload artifacts for debugging if needed
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: build/
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          path: build/
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3